name: CI/CD for Vite React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Ensure this matches your project’s requirements

      - name: Install dependencies
        run: npm install

      # Comment or remove the test step if no test script is defined
      - name: Run tests
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test
          else
            echo "No test script defined in package.json"
          fi

      - name: Build Vite app
        run: npm run build
